config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # ignore ^

  root "books#index"

  resources :books, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews

  validates :title, presence: true
  validates :author, presence: true


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book

  validates :rating, presence: true
  validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @reviews = @book.reviews
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:notice] = "Good it worked"
      redirect_to @book
    else
      flash[:alert]
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


def index

end

def new
  @book = Book.find(params[:book_id])
  @review = Review.new

end

def create
  @review = Review.new(review_params)
  @book = Book.find(params[:book_id])
  @review.book = @book

  if @review.save
    flash[:notice] = "OMG YOU MADE A REVIEW GOOD JOB"
    redirect_to @book
  else
    flash.now[:alert] = @review.errors.full_messages.to_sentence
    render :new
  end
end

private

def review_params
  params.require(:review).permit(:rating, :body)
end

end

app/views/books/index.html.erb
<h1>Books</h1>


<% @books.each do |book| %>
<ul>
  <li>
    <%= link_to book.title, book_path(book) %>
  </li>
</ul>
<% end %>

app/views/books/new.html.erb
<h2> New Book Page </h2>

<h3>Review</h3>
<%= form_for [@book, @review] do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :author %>
<%= f.text_field :author %>

<%= f.submit "Add Book" %>

<% end %>

app/views/books/show.html.erb
<h2>Show page for<%= @book.title%></h2>

<p>
  <%= @book.author %>
</p>

<p>
  <%= @book.isbn %>
</p>

<h4>Reviews</h4>
<% @reviews.each do |review| %>
<ul>
  <li>
    <%= review.rating %>
    <%= review.body %>
  </li>
</ul>

<% end %>

<h2><%= link_to "Add a Review", new_book_review_path(@book) %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodreadsRailsReview</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Goodreads Rails Review</a></h1>
      </li>
    </ul>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>

  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/reviews/new.html.erb
<h1>Review form for <%= @book.title %></h1>

<h3>Review</h3>
<%= form_for [@book, @review] do |f| %>
<%= f.label :rating %>
<%= f.text_field :rating %>

<%= f.label :body, "Review" %>
<%= f.text_field :body %>

<%= f.submit "Add Review" %>

<% end %>